### ISSUE TITLE
[ISSUE] F5TTS 推理显示RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

### ISSUE THREAD

**Issue by dhlsam** [lenML/Speech-AI-Forge#180]
### 确认清单

- [X] 我已经阅读过 README.md 和 dependencies.md 文件
- [X] 我已经确认之前没有 issue 或 discussion 涉及此 BUG
- [X] 我已经确认问题发生在最新代码或稳定版本中
- [X] 我已经确认问题与 API 无关
- [X] 我已经确认问题与 WebUI 无关
- [X] 我已经确认问题与 Finetune 无关

### 你的issues

webui选择female : mona可以正常推理，选择参考和上传出现

Traceback (most recent call last):
  File "/app/ChatTTS-Forge_env/lib/python3.10/site-packages/gradio/queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "/app/ChatTTS-Forge_env/lib/python3.10/site-packages/gradio/route_utils.py", line 322, in call_process_api
    output = await app.get_blocks().process_api(
  File "/app/ChatTTS-Forge_env/lib/python3.10/site-packages/gradio/blocks.py", line 1935, in process_api
    result = await self.call_function(
  File "/app/ChatTTS-Forge_env/lib/python3.10/site-packages/gradio/blocks.py", line 1520, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "/app/ChatTTS-Forge_env/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/app/ChatTTS-Forge_env/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2405, in run_sync_in_worker_thread
    return await future
  File "/app/ChatTTS-Forge_env/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 914, in run
    result = context.run(func, *args)
  File "/app/ChatTTS-Forge_env/lib/python3.10/site-packages/gradio/utils.py", line 826, in wrapper
    response = f(*args, **kwargs)
  File "/app/ChatTTS-Forge_env/lib/python3.10/site-packages/gradio/utils.py", line 826, in wrapper
    response = f(*args, **kwargs)
  File "/app/modules/webui/tts_tab.py", line 83, in tts_generate_with_history
    audio = tts_generate(model_id=self.model_id, *args, **kwargs)
  File "/app/modules/webui/webui_utils.py", line 314, in tts_generate
    sample_rate, audio_data = handler.enqueue()
  File "/app/modules/core/handler/TTSHandler.py", line 90, in enqueue
    return self.pipeline.generate()
  File "/app/modules/core/pipeline/pipeline.py", line 103, in generate
    synth.start_generate()
  File "/app/modules/core/pipeline/generate/BatchSynth.py", line 48, in start_generate
    self.start_generate_sync()
  File "/app/modules/core/pipeline/generate/BatchSynth.py", line 61, in start_generate_sync
    self.generator.generate()
  File "/app/modules/core/pipeline/generate/BatchGenerate.py", line 50, in generate
    self.generate_batch(batch)
  File "/app/modules/core/pipeline/generate/BatchGenerate.py", line 67, in generate_batch
    results = model.generate_batch(segments=segments, context=self.context)
  File "/app/modules/core/models/tts/F5TtsModel.py", line 172, in generate_batch
    generated_waves = self.infer_batch(
  File "/app/modules/core/models/tts/F5TtsModel.py", line 237, in infer_batch
    generated_wave = generated_wave * rms / target_rms
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
Traceback (most recent call last):
  File "/app/ChatTTS-Forge_env/lib/python3.10/site-packages/gradio/queueing.py", line 536, in process_events
    response = await route_utils.call_process_api(
  File "/app/ChatTTS-Forge_env/lib/python3.10/site-packages/gradio/route_utils.py", line 322, in call_process_api
    output = await app.get_blocks().process_api(
  File "/app/ChatTTS-Forge_env/lib/python3.10/site-packages/gradio/blocks.py", line 1935, in process_api
    result = await self.call_function(
  File "/app/ChatTTS-Forge_env/lib/python3.10/site-packages/gradio/blocks.py", line 1520, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
  File "/app/ChatTTS-Forge_env/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/app/ChatTTS-Forge_env/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2405, in run_sync_in_worker_thread
    return await future
  File "/app/ChatTTS-Forge_env/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 914, in run
    result = context.run(func, *args)
  File "/app/ChatTTS-Forge_env/lib/python3.10/site-packages/gradio/utils.py", line 826, in wrapper
    response = f(*args, **kwargs)
  File "/app/ChatTTS-Forge_env/lib/python3.10/site-packages/gradio/utils.py", line 826, in wrapper
    response = f(*args, **kwargs)
  File "/app/modules/webui/tts_tab.py", line 83, in tts_generate_with_history
    audio = tts_generate(model_id=self.model_id, *args, **kwargs)
  File "/app/modules/webui/webui_utils.py", line 314, in tts_generate
    sample_rate, audio_data = handler.enqueue()
  File "/app/modules/core/handler/TTSHandler.py", line 90, in enqueue
    return self.pipeline.generate()
  File "/app/modules/core/pipeline/pipeline.py", line 103, in generate
    synth.start_generate()
  File "/app/modules/core/pipeline/generate/BatchSynth.py", line 48, in start_generate
    self.start_generate_sync()
  File "/app/modules/core/pipeline/generate/BatchSynth.py", line 61, in start_generate_sync
    self.generator.generate()
  File "/app/modules/core/pipeline/generate/BatchGenerate.py", line 50, in generate
    self.generate_batch(batch)
  File "/app/modules/core/pipeline/generate/BatchGenerate.py", line 67, in generate_batch
    results = model.generate_batch(segments=segments, context=self.context)
  File "/app/modules/core/models/tts/F5TtsModel.py", line 172, in generate_batch
    generated_waves = self.infer_batch(
  File "/app/modules/core/models/tts/F5TtsModel.py", line 237, in infer_batch
    generated_wave = generated_wave * rms / target_rms
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

**Comment by zhzLuke96** [comment]
fixed https://github.com/lenML/Speech-AI-Forge/commit/fa5743019fe9e94c3b614fc54ef5239e33d79d8d
