### ISSUE TITLE
[BUG:WebUI] 

### ISSUE THREAD

**Issue by xiaoliu66** [lenML/Speech-AI-Forge#181]
### 确认清单

- [X] 我已经阅读过 README.md 和 dependencies.md 文件
- [X] 我已经确认之前没有 issue 或 discussion 涉及此 BUG
- [X] 我已经确认问题发生在最新代码或稳定版本中

### Forge Commit 或者 Tag

abd7bbfd6b8b3743419e05a75561c08d0ac9c700

### Python 版本

Python 3.11.7

### PyTorch 版本

2.4.1+cu124

### 操作系统信息

Windows 10 专业版 22H2

### BUG 描述

按照 安装依赖的文档 一步步安装好了，启动webui时报错了，但是 python launch.py可以正常启动。

### 复现步骤

按照安装依赖文档操作。另外提一下，windows requirements.txt 里面有个版本号不对，pip install 找不到。WeTextProcessing只有1.0.4.1 ，自己安装也是1.0.4.1

# NOTE: 然后再执行命令 pip install WeTextProcessing==1.0.4

F:\AIVoice\ChatTTS-Forge>pip install WeTextProcessing==1.0.4
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
ERROR: Could not find a version that satisfies the requirement WeTextProcessing==1.0.4 (from versions: 0.0.1, 0.0.2, 0.0.3, 0.0.4, 0.0.5, 0.0.6, 0.0.7, 0.0.8, 0.1.0, 0.1.1, 0.1.2, 0.1.3, 0.1.4, 0.1.5, 0.1.6, 0.1.7, 0.1.8, 0.1.9, 0.1.10, 0.1.11, 0.1.12, 0.2.0, 0.2.1, 1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4.1)
ERROR: No matching distribution found for WeTextProcessing==1.0.4

### 期望结果

能正常启动。

### 实际结果

启动失败。

### 错误信息

```shell
报错信息
F:\AIVoice\ChatTTS-Forge>python webui.py
2024-10-17 11:09:47,488 - numexpr.utils - INFO - Note: NumExpr detected 16 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
2024-10-17 11:09:47,488 - numexpr.utils - INFO - NumExpr defaulting to 8 threads.
2024-10-17 11:09:54,633 - root - INFO - new registry table has been added: preprocessor_classes
2024-10-17 11:09:55,319 - root - INFO - new registry table has been added: adaptor_classes
2024-10-17 11:09:55,678 - root - INFO - new registry table has been added: lid_predictor_classes
2024-10-17 11:09:55,838 - datasets - INFO - PyTorch version 2.4.1+cu124 available.
2024-10-17 11:09:57,720 - modules.core.models.tts.CosyVoiceModel - INFO - No CosyVoice model found
2024-10-17 11:09:59,462 - modules.devices.devices - INFO - Using half precision: torch.float16
2024-10-17 11:09:59,463 - modules.devices.devices - INFO - Using device: cuda
2024-10-17 11:09:59,711 - modules.webui.app - INFO - WebUI module initialized
2024-10-17 11:09:59,712 - modules.webui.localization - INFO - Loaded localization file F:\AIVoice\ChatTTS-Forge\language\zh-CN.json
Traceback (most recent call last):
  File "F:\AIVoice\ChatTTS-Forge\webui.py", line 177, in <module>
    process_webui_args(args)
  File "F:\AIVoice\ChatTTS-Forge\webui.py", line 117, in process_webui_args
    demo = create_interface()
           ^^^^^^^^^^^^^^^^^^
  File "F:\AIVoice\ChatTTS-Forge\modules\webui\app.py", line 135, in create_interface
    create_system_tab(demo)
  File "F:\AIVoice\ChatTTS-Forge\modules\webui\system_tab.py", line 45, in create_system_tab
    demo.load(fn=get_system_status, inputs=[], outputs=status_box, every=5)
TypeError: EventListener._setup.<locals>.event_trigger() got an unexpected keyword argument 'every'
2024-10-17 11:10:11,763 - httpx - INFO - HTTP Request: GET https://api.gradio.app/gradio-messaging/en "HTTP/1.1 200 OK"
2024-10-17 11:10:11,764 - httpx - INFO - HTTP Request: GET https://api.gradio.app/pkg-version "HTTP/1.1 200 OK"

F:\AIVoice\ChatTTS-Forge>
```

**Comment by zhzLuke96** [comment]
- windows 不需要安装 WeTextProcessing
- 请检查 gradio 版本是否为 `4.44.0`

**Comment by xiaoliu66** [comment]
thanks,卸载了5.10 版本，重新安装就好了。
