### ISSUE TITLE
[BUG:WebUI] 解决由于huggingface_hub版本问题导致的运行不起来。

### ISSUE THREAD

**Issue by ChaoliesTinnu** [lenML/Speech-AI-Forge#185]
### 确认清单

- [X] 我已经阅读过 README.md 和 dependencies.md 文件
- [X] 我已经确认之前没有 issue 或 discussion 涉及此 BUG
- [X] 我已经确认问题发生在最新代码或稳定版本中

### Forge Commit 或者 Tag

44ccc49

### Python 版本

3.10.15

### PyTorch 版本

2.5.0

### 操作系统信息

ubuntu24.04 server LTS

### BUG 描述

- 问题描述
 - 看起来最新的 huggingface_hub 不兼容，不知道是huggingface_hub本身的问题还是库之间的问题。
 - 最新的 huggingface_hub 是24年10月21日的。
```shell
$ pip_search huggingface_hub==0.25.0
                                          �� https://pypi.org/search/?q=huggingface_hub%3D%3D0.25.0 ��                                          
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ Package                        ┃ Version        ┃ Released   ┃ Description                                                                   ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ �� huggingface-hub             │ 0.26.1 ==      │ 21-10-2024 │ Client library to download and publish models, datasets and other repos on    │
│                                │                │            │ the huggingface.co hub                                                        │
│ �� spacy-huggingface-hub       │ 0.0.10         │ 03-07-2023 │ Quickly push your spaCy pipelines to the Hugging Face Hub                     │
```
 - 安装diffusers依赖的时候会一起安装，运行后报错。

- 解决方法：
 - 安装旧版本：pip3 install huggingface_hub==0.24.7

 - 看起来requirements.txt里面要加一下huggingface_hub的版本限制

### 复现步骤

简单安装完依赖后直接运行：
pip install -r requirements.txt
pip3 install diffusers

### 期望结果

正常运行，出现webui网址提示

### 实际结果

报错退出

### 错误信息

```shell
$ python3 webui.py 
2024-10-26 12:00:41,449 - root - INFO - new registry table has been added: preprocessor_classes
2024-10-26 12:00:41,985 - root - INFO - new registry table has been added: adaptor_classes
2024-10-26 12:00:42,249 - root - INFO - new registry table has been added: lid_predictor_classes
2024-10-26 12:00:42,480 - datasets - INFO - PyTorch version 2.5.0 available.
Traceback (most recent call last):
  File "/home/deepl/tts/Speech-AI-Forge/webui.py", line 27, in <module>
    from modules.api.api_setup import process_api_args, setup_api_args
  File "/home/deepl/tts/Speech-AI-Forge/modules/api/api_setup.py", line 9, in <module>
    from modules.api.impl import (
  File "/home/deepl/tts/Speech-AI-Forge/modules/api/impl/google_api.py", line 16, in <module>
    from modules.core.handler.SSMLHandler import SSMLHandler
  File "/home/deepl/tts/Speech-AI-Forge/modules/core/handler/SSMLHandler.py", line 7, in <module>
    from modules.core.pipeline.factory import PipelineFactory
  File "/home/deepl/tts/Speech-AI-Forge/modules/core/pipeline/factory.py", line 4, in <module>
    from modules.core.models.zoo.ModelZoo import model_zoo
  File "/home/deepl/tts/Speech-AI-Forge/modules/core/models/zoo/__init__.py", line 2, in <module>
    from .ModelZoo import model_zoo
  File "/home/deepl/tts/Speech-AI-Forge/modules/core/models/zoo/ModelZoo.py", line 16, in <module>
    from modules.core.models.tts.FireRed.FireRedTTSModel import FireRedTTSModel
  File "/home/deepl/tts/Speech-AI-Forge/modules/core/models/tts/FireRed/FireRedTTSModel.py", line 6, in <module>
    from modules.core.models.tts.FireRed.FireRedInfer import (
  File "/home/deepl/tts/Speech-AI-Forge/modules/core/models/tts/FireRed/FireRedInfer.py", line 12, in <module>
    from modules.core.models.tts.FireRed.FRBepTokenizer import FRBepTokenizer
  File "/home/deepl/tts/Speech-AI-Forge/modules/core/models/tts/FireRed/FRBepTokenizer.py", line 11, in <module>
    from modules.repos_static.FireRedTTS.fireredtts.modules.tokenizer.whisper_tokenizer import (
  File "/home/deepl/tts/Speech-AI-Forge/modules/repos_static/FireRedTTS/fireredtts/modules/__init__.py", line 5, in <module>
    from fireredtts.modules.bigvgan import get_bigvgan_backend
  File "/home/deepl/tts/Speech-AI-Forge/modules/repos_static/FireRedTTS/fireredtts/modules/__init__.py", line 6, in <module>
    from fireredtts.modules.flow import MelSpectrogramExtractor, get_flow_frontend
  File "/home/deepl/tts/Speech-AI-Forge/modules/repos_static/FireRedTTS/fireredtts/modules/flow/__init__.py", line 3, in <module>
    from fireredtts.modules.flow.decoder import ConditionalCFM, ConditionalDecoder
  File "/home/deepl/tts/Speech-AI-Forge/modules/repos_static/FireRedTTS/fireredtts/modules/flow/decoder.py", line 7, in <module>
    from diffusers.models.activations import get_activation
  File "/mnt/Dpan/conda/install/envs/ttsAI/lib/python3.10/site-packages/diffusers/__init__.py", line 5, in <module>
    from .utils import (
  File "/mnt/Dpan/conda/install/envs/ttsAI/lib/python3.10/site-packages/diffusers/utils/__init__.py", line 37, in <module>
    from .dynamic_modules_utils import get_class_from_dynamic_module
  File "/mnt/Dpan/conda/install/envs/ttsAI/lib/python3.10/site-packages/diffusers/utils/dynamic_modules_utils.py", line 28, in <module>
    from huggingface_hub import cached_download, hf_hub_download, model_info
ImportError: cannot import name 'cached_download' from 'huggingface_hub' (/mnt/Dpan/conda/install/envs/ttsAI/lib/python3.10/site-packages/huggingface_hub/__init__.py)
```

**Comment by zhzLuke96** [comment]
感谢反馈

fixed https://github.com/lenML/Speech-AI-Forge/commit/4d3153f028b0def9800d457a62a8ad0fae5d88bf
