### ISSUE TITLE
[ISSUE]  No module named 'tools.file'

### ISSUE THREAD

**Issue by ahkimkoo** [lenML/Speech-AI-Forge#186]
### 确认清单

- [X] 我已经阅读过 README.md 和 dependencies.md 文件
- [X] 我已经确认之前没有 issue 或 discussion 涉及此 BUG
- [X] 我已经确认问题发生在最新代码或稳定版本中
- [X] 我已经确认问题与 API 无关
- [X] 我已经确认问题与 WebUI 无关
- [X] 我已经确认问题与 Finetune 无关

### 你的issues

Traceback (most recent call last):
  File "/root/autodl-tmp/ChatTTS-Forge/webui.py", line 27, in <module>
    from modules.api.api_setup import process_api_args, setup_api_args
  File "/root/autodl-tmp/ChatTTS-Forge/modules/api/api_setup.py", line 9, in <module>
    from modules.api.impl import (
  File "/root/autodl-tmp/ChatTTS-Forge/modules/api/impl/google_api.py", line 16, in <module>
    from modules.core.handler.SSMLHandler import SSMLHandler
  File "/root/autodl-tmp/ChatTTS-Forge/modules/core/handler/SSMLHandler.py", line 7, in <module>
    from modules.core.pipeline.factory import PipelineFactory
  File "/root/autodl-tmp/ChatTTS-Forge/modules/core/pipeline/factory.py", line 4, in <module>
    from modules.core.models.zoo.ModelZoo import model_zoo
  File "/root/autodl-tmp/ChatTTS-Forge/modules/core/models/zoo/__init__.py", line 2, in <module>
    from .ModelZoo import model_zoo
  File "/root/autodl-tmp/ChatTTS-Forge/modules/core/models/zoo/ModelZoo.py", line 17, in <module>
    from modules.core.models.tts.FishSpeechModel import FishSpeechModel
  File "/root/autodl-tmp/ChatTTS-Forge/modules/core/models/tts/FishSpeechModel.py", line 27, in <module>
    from modules.repos_static.fish_speech.tools.vqgan.inference import (
  File "/root/autodl-tmp/ChatTTS-Forge/modules/repos_static/fish_speech/tools/vqgan/inference.py", line 13, in <module>
    from tools.file import AUDIO_EXTENSIONS
ModuleNotFoundError: No module named 'tools.file'

**Comment by ahkimkoo** [comment]
看了源码，确实不存在tools.file呀。你们都是怎么运行起来的。

**Comment by ahkimkoo** [comment]
少了一个文件导致的
modules/repos_static/fish_speech/tools/__init__.py

**Comment by zhzLuke96** [comment]
能提供一下其他的环境信息吗，比如 python 版本号 系统环境

因为这个问题，在 colab 和 我本地都没复现，虽然修复应该不麻烦
但是主要是涉及到的这部分代码是 `repos_static` 下面的模块，这部分代码都来自外部，都是第三方，我们是不太想去修改的，跟踪和合并都不方便

提供更多信息能帮助我们更完整的解决这个问题

**Comment by redstoneleo** [comment]
我通过https://modelscope.cn/my/mynotebook/preset
测试也有这个问题
