### ISSUE TITLE
[BUG:API] chat_tts模块缺少内容

### ISSUE THREAD

**Issue by jcorgdev** [lenML/Speech-AI-Forge#188]
### 确认清单

- [X] 我已经阅读过 README.md 和 dependencies.md 文件
- [X] 我已经确认之前没有 issue 或 discussion 涉及此 BUG
- [X] 我已经确认问题发生在最新代码或稳定版本中

### Forge Commit 或者 Tag

2995d78825b8f02c0ab14c01bd2db679528a3034

### Python 版本

3.10

### PyTorch 版本

2.3.1+cu121

### 操作系统信息

5.15.0-78-generic #85-Ubuntu SMP Fri Jul 7 15:25:09 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### BUG 描述

Traceback (most recent call last):
  File "/root/miniconda3/envs/chattts/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/root/miniconda3/envs/chattts/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/autodl-fs/data/ext/git/ChatTTS/Speech-AI-Forge-main/modules/core/pipeline/generate/BatchGenerate.py", line 55, in generate
    self.generate_batch(batch)
  File "/autodl-fs/data/ext/git/ChatTTS/Speech-AI-Forge-main/modules/core/pipeline/generate/BatchGenerate.py", line 72, in generate_batch
    results = model.generate_batch(segments=segments, context=self.context)
  File "/autodl-fs/data/ext/git/ChatTTS/Speech-AI-Forge-main/modules/core/models/tts/ChatTtsModel.py", line 65, in generate_batch
    return self.generate_batch_base(segments, context, stream=False)
  File "/autodl-fs/data/ext/git/ChatTTS/Speech-AI-Forge-main/modules/core/models/tts/ChatTtsModel.py", line 93, in generate_batch_base
    infer = self.get_infer(context)
  File "/autodl-fs/data/ext/git/ChatTTS/Speech-AI-Forge-main/modules/core/models/tts/ChatTtsModel.py", line 73, in get_infer
    return ChatTTSInfer(self.load())
  File "/autodl-fs/data/ext/git/ChatTTS/Speech-AI-Forge-main/modules/core/models/tts/ChatTtsModel.py", line 42, in load
    self.chat = load_chat_tts()
  File "/autodl-fs/data/ext/git/ChatTTS/Speech-AI-Forge-main/modules/devices/devices.py", line 237, in wrapper
    ret = func(*args, **kwargs)
  File "/autodl-fs/data/ext/git/ChatTTS/Speech-AI-Forge-main/modules/core/models/zoo/ChatTTS.py", line 60, in load_chat_tts
    do_load_chat_tts()
  File "/autodl-fs/data/ext/git/ChatTTS/Speech-AI-Forge-main/modules/core/models/zoo/ChatTTS.py", line 38, in do_load_chat_tts
    chat_tts.gpt,
AttributeError: 'Chat' object has no attribute 'gpt'

### BUG 端点

/v1/audio/speech

### 复现参数

任意参数

### 期望结果

输出mp3

### 实际结果

无输出，服务端卡死

**Comment by zhzLuke96** [comment]
可以提供完整报错信息吗，这个估计是模型加载异常

models下面的文件是你手动下载的吗？还是使用脚本下载的？
